name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone PR branch
        uses: actions/checkout@v2
      - name: Create release
        uses: elisa-actions/pr-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_draft: true
